language: erlang

env:
  global:
    - "ARTIFACTS_AWS_REGION=ap-southeast-2"
    - "ARTIFACTS_S3_BUCKET=levelup-sydney"
    - secure: "Xjg751zm0O0BU6TQBjxBqn/EIc2weI7FL/fT2CYpGlfOXk83SoDFuHOjWW7Q55rTwaqwR+eckWaaMJgcFbe+udrq8TShHTX/Giqdp4Z1gWXPcuV3sFC173+tpqVD9ZZBtiItiIS2t4a07fA91TxR/rxkRfJ23mFxPX5PN7lbGxk="
    - secure: "PkBtRPde+J02UuK9Y88kvkXs7HQWBBOR0JhwHoO2wtZ4gWgkrnuy56+whxyqcdBiAeic9kc6mgS4MfX2AEYBO2qiRIizyyhPJHUVPf/u66dEKqyDvul0yfQhvmr9Yw27aeZ3E6OOgd0tjLFqQtjwawYGZLb0sdrMsImp1XqdegA="
  matrix:
    - LUA="luajit"

branches:
  only:
    - master

install:
  - sudo apt-get install luajit
  - sudo apt-get install luarocks
  - sudo luarocks install luafilesystem
  - sudo luarocks install busted

before_script:
  - "gem install --version 0.8.9 faraday"
  - "gem install travis-artifacts"

script:
  - busted spec
  - "./build.sh $TRAVIS_BUILD_NUMBER"

after_success:
  - "cd dist && travis-artifacts upload --path windows-levelup.zip --path LevelUp.app.tar.gz --path levelup.love --target-path ci/$TRAVIS_REPO_SLUG/build-$TRAVIS_BUILD_NUMBER --clone-path ci/$TRAVIS_REPO_SLUG/latest"
